Repository jeremielenoir/oostaoo-site, pull requests merged in 2023-02, with the labels that each got.

#64 Fix/Fixes on scroll behavior and dynamic offsets
  components/ListButtonNav/ListButtonNav.tsx
  components/nav/Nav.tsx
  types/types.ts
Labels: enhancement, merge request

#67 Feature/harmonize padding
  components/ContactForm/ContactForm.module.css
  components/JobOffers/JobOffers.module.css
  components/LogoWrapper/LogosWrapper.module.css
  pages/Home.module.css
Labels: enhancement, merge request

#69 [Updated]Added test correctly display text hero component and add set…
  components/HeaderHero/HeaderHero.test.js
  jest.config.js
  package-lock.json
  package.json
  setupTest.js
Labels: enhancement, merge request

#72 [Updated]Added test for intro component
  components/Intro/Intro.test.js
Labels: enhancement, merge request

#83 Fix/#82/TS_and_ESlint_import_conflict
  .eslintrc.json
  .prettierrc.json
  assets/Intro.js
  assets/Logos.js
  assets/Services.js
  assets/Titles.js
  assets/jobData.ts
  components/ContactForm/ContactForm.tsx
  components/HeaderHero/HeaderHero.tsx
  components/Intro/Intro.tsx
  components/JobOffers/JobOffer.tsx
  components/JobOffers/JobOffers.tsx
  components/ListButtonNav/ListButtonNav.tsx
  components/LogoWrapper/LogosWrapper.tsx
  components/SectionReferencesTechnos/SectionReferencesTechnos.tsx
  components/SectionTitle/SectionTitle.tsx
  components/ServiceContainer/ServiceContainer.tsx
  components/Services/Services.tsx
  components/nav/Nav.tsx
  pages/_app.tsx
  pages/index.tsx
  tsconfig.json
Labels: bug, merge request

#84 Fix/#82/ts and e slint import conflict
  .eslintrc.json
  .husky/pre-commit
  components/HeaderHero/HeaderHero.test.js
  components/Intro/Intro.test.js
  components/JobOffers/JobOffer.tsx
  components/JobOffers/JobOffers.tsx
  components/SectionReferencesTechnos/SectionReferencesTechnos.tsx
  components/nav/Nav.tsx
  pages/_app.tsx
  pages/api/hello.ts
  styles/theme.ts
Labels: bug, merge request

#87 Feature/#79/logo wrapper component testing
  components/LogoWrapper/LogoWrapper.test.js
Labels: enhancement

#91 Feature/#88/section references technos component testing
  components/LogoWrapper/LogosWrapper.module.css
  components/LogoWrapper/LogosWrapper.tsx
  components/SectionReferencesTechnos/SectionReferencesTechnos.test.js
  components/SectionReferencesTechnos/SectionReferencesTechnos.tsx
  components/SectionTitle/SectionTitle.tsx
  pages/index.tsx
Labels: enhancement

#97 Feature/#96/test job offers component
  components/JobOffers/JobOffers.test.tsx
  components/JobOffers/JobOffers.tsx
Labels: enhancement

#109 fix bugs loading technos images and optimization HeaderHero image
  components/HeaderHero/HeaderHero.tsx
  components/LogoWrapper/LogoWrapper.test.js
  components/LogoWrapper/LogosWrapper.tsx
  public/assets/technos/javascript.png
Labels: merge request
