Repository jeremielenoir/oostaoo-site, pull requests merged in 2023-01, with the labels that each got.

#26 Documentation
  documentation/MCD-oostaoo-site.excalidraw
  documentation/MCD-oostaoo-site.png
  documentation/user-stories.md
Labels: enhancement

#31 Feature/#30/Hero Header
  components/HeaderHero/HeaderHero.module.css
  components/HeaderHero/HeaderHero.tsx
  pages/index.tsx
Labels: enhancement, merge request

#33 Feature/#32/Intro
  components/Intro/Intro.module.css
  components/Intro/Intro.tsx
  pages/index.tsx
Labels: enhancement, merge request

#35 Feature/create nav#22
  components/nav/Nav.module.css
  components/nav/Nav.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  styles/index.css
  styles/theme.ts
Labels: enhancement, merge request

#36 Feature/#34/reusable title component+services section
  assets/Services.js
  assets/Titles.js
  components/SectionTitle/SectionTitle.module.css
  components/SectionTitle/SectionTitle.tsx
  components/ServiceContainer/ServiceContainer.module.css
  components/ServiceContainer/ServiceContainer.tsx
  components/Services/Services.module.css
  components/Services/Services.tsx
  pages/index.tsx
Labels: enhancement, merge request

#44 Feature/New component + Intro.js
  assets/Intro.js
  components/HeaderHero/HeaderHero.module.css
  components/Intro/Intro.module.css
  components/Intro/Intro.tsx
Labels: enhancement, merge request

#42 Fix/Icons + some CSS
  assets/Services.js
  assets/Titles.js
  components/Intro/Intro.module.css
  components/ServiceContainer/ServiceContainer.module.css
  components/ServiceContainer/ServiceContainer.tsx
  components/Services/Services.tsx
  pages/_app.tsx
Labels: enhancement, merge request

#46 Feature/contact form#40
  components/ContactForm/ContactForm.module.css
  components/ContactForm/ContactForm.tsx
  components/JobOffers/JobOffers.tsx
  package-lock.json
  package.json
  pages/Home.module.css
  pages/index.tsx
  tsconfig.json
Labels: enhancement, merge request

#50 [Fix]Fix bug with ghostContainer missed after merge issue 38
  components/nav/Nav.tsx
  pages/index.tsx
Labels: enhancement, merge request

#53 use of useState and useEffect to make the functionnality to respect t…
  components/JobOffers/JobOffers.tsx
  components/nav/Nav.module.css
  components/nav/Nav.tsx
  package-lock.json
  package.json
  pages/index.tsx
  styles/theme.ts
Labels: bug, merge request

#56 Feature/Added all icons
  public/assets/logo/Bootstrap.png
  public/assets/logo/CSS3.png
  public/assets/logo/HTML5.png
  public/assets/logo/JQuery.png
  public/assets/logo/JavaScript.png
  public/assets/logo/Kibana.png
  public/assets/logo/NodeJS.png
  public/assets/logo/PHP.png
  public/assets/logo/Python.png
  public/assets/logo/Swift.png
  public/assets/logo/VueJS.png
  public/assets/logo/Zend.png
  public/assets/logo/android.png
  public/assets/logo/angular.png
  public/assets/logo/git.png
  public/assets/logo/iOS.png
  public/assets/logo/react.png
  public/assets/logo/symfony.png
  public/assets/references/aramisauto.png
  public/assets/references/continental.png
  public/assets/references/maisondumonde.png
  public/assets/references/mazarinne.png
  public/assets/references/mugler.png
  public/assets/references/poliris.png
  public/assets/references/sarenza.png
  public/assets/references/tagcommander.png
  public/assets/references/wynd.png
Labels: enhancement

#54 Feature/#51/services section text toggle
  components/SectionTitle/SectionTitle.module.css
  components/ServiceContainer/ServiceContainer.module.css
  components/ServiceContainer/ServiceContainer.tsx
  components/Services/Services.module.css
Labels: enhancement, merge request

#59 feature/#58/prisma postgresdb init
  prisma/schema.prisma
Labels: Database
